# Generated by Django 4.2 on 2026-09-24 07:37

import apps.accounts.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def fix_blank_and_duplicate_phones(apps, schema_editor):
    """Le champ phone devient unique dans cette migration. On doit d'abord :
    - convertir les valeurs vides ('') en NULL (une seule valeur '' bloquerait
      l'index unique dès le deuxième utilisateur sans téléphone) ;
    - dédupliquer les numéros identiques en gardant le compte le plus ancien et
      en mettant les autres à NULL, plutôt que d'échouer la migration ou de
      supprimer des comptes."""
    User = apps.get_model('accounts', 'User')

    User.objects.filter(phone='').update(phone=None)

    seen = {}
    duplicates = []
    for user in User.objects.exclude(phone=None).order_by('id').only('id', 'phone'):
        if user.phone in seen:
            duplicates.append(user.id)
        else:
            seen[user.phone] = user.id
    if duplicates:
        User.objects.filter(id__in=duplicates).update(phone=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='KycDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('RCCM', 'RCCM'), ('ID_NATIONALE', 'Identification nationale'), ('PIECE_GERANT', "Pièce d'identité du gérant")], max_length=20)),
                ('file', models.FileField(storage=apps.accounts.models.KycPrivateStorage(), upload_to='')),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Le numéro doit être au format +243 suivi de 9 chiffres.', regex='^\\+243\\d{9}$')])),
                ('purpose', models.CharField(choices=[('REGISTER', 'Inscription'), ('LOGIN', 'Connexion'), ('PASSWORD_RESET', 'Réinitialisation du mot de passe')], max_length=20)),
                ('code_hash', models.CharField(max_length=128)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True),
        ),
        # Étape intermédiaire : rendre la colonne nullable SANS la contrainte unique,
        # pour que le RunPython puisse mettre '' et les doublons à NULL sans violer
        # de contrainte. L'unicité définitive est ajoutée juste après, une fois les
        # données propres (portable SQLite/MySQL, cf. CDC 2.6).
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Le numéro doit être au format +243 suivi de 9 chiffres.', regex='^\\+243\\d{9}$')]),
        ),
        migrations.RunPython(fix_blank_and_duplicate_phones, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro doit être au format +243 suivi de 9 chiffres.', regex='^\\+243\\d{9}$')]),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['phone', 'purpose', 'is_used'], name='accounts_ot_phone_98e2f1_idx'),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='business_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to='accounts.businessprofile'),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
