# Generated by Django 4.2 on 2026-09-24 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_post_last_score_update_post_likes_count_and_more'),
        ('accounts', '0005_kycdocument_otpcode_user_phone_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.city'),
        ),
    ]
