# Generated by Django 4.2 on 2026-09-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='trust_score',
            field=models.FloatField(default=3.5),
        ),
    ]
