# Generated by Django 4.2 on 2026-04-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reply_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='reply_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
