# Generated by Django 4.2 on 2026-09-24 08:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def backfill_reviewed_user(apps, schema_editor):
    """reviewed_user est nouveau : pour les avis déjà en base (avant l'affaire
    conclue, apps.reputation), la personne évaluée est par convention le
    vendeur de l'annonce concernée — c'était déjà implicitement le sens de ces
    avis (voir l'action 'reply', historiquement réservée au vendeur)."""
    Review = apps.get_model('interactions', 'Review')
    for review in Review.objects.select_related('post').filter(reviewed_user__isnull=True):
        review.reviewed_user_id = review.post.seller_id
        review.save(update_fields=['reviewed_user'])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reputation', '0001_initial'),
        ('interactions', '0006_review_reply_at_review_reply_content'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reputation.deal'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewed_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_reviewed_user, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('deal', 'user')},
        ),
    ]
