# Generated by Django 4.2 on 2026-09-24 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_marketplacesettings_post_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interactions', '0007_alter_review_unique_together_review_deal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('COMMENT', 'Nouveau commentaire'), ('CONTACT', 'Demande de contact'), ('EXCHANGE', "Proposition d'échange"), ('MESSAGE', 'Nouveau message'), ('EXPIRATION', 'Annonce bientôt expirée'), ('SYSTEM', 'Système')], max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='marketplace.post'),
        ),
        migrations.CreateModel(
            name='ContactStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_stats', to='marketplace.post')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Statistique de contact',
                'ordering': ['-date'],
                'unique_together': {('post', 'date')},
            },
        ),
    ]
