# Generated by Django 4.2 on 2026-04-24 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_postviewstat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postviewstat',
            options={'ordering': ['-date'], 'verbose_name': 'Statistique de vue'},
        ),
    ]
