# Generated by Django 4.2 on 2026-04-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_postviewstat_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_exchangeable',
            field=models.BooleanField(default=True, verbose_name='Echangeable'),
        ),
    ]
