# Generated by Django 4.2 on 2026-04-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_post_is_exchangeable'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_score_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='visibility_score',
            field=models.FloatField(default=0.0),
        ),
    ]
