# Generated by Django 4.2 on 2026-09-24 11:02

from datetime import timedelta

from django.db import migrations, models


def backfill_expires_at(apps, schema_editor):
    """Les annonces déjà en base n'ont pas d'expires_at : on part de la même
    règle que Post.save() (created_at + expiration_days), avec la valeur par
    défaut de MarketplaceSettings (aucune ligne de paramètres n'existe encore
    à ce stade des migrations)."""
    Post = apps.get_model('marketplace', 'Post')
    expiration_days = 60
    for post in Post.objects.filter(expires_at__isnull=True):
        post.expires_at = post.created_at + timedelta(days=expiration_days)
        post.save(update_fields=['expires_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_post_comments_count_post_shares_count_postuniqueview'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_days', models.PositiveIntegerField(default=60)),
                ('trash_retention_days', models.PositiveIntegerField(default=30)),
                ('expiring_soon_warning_days', models.PositiveIntegerField(default=3)),
            ],
            options={
                'verbose_name': 'Paramètres de la marketplace',
                'verbose_name_plural': 'Paramètres de la marketplace',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='expiring_soon_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'En pause'), ('SOLD', 'Vendue'), ('EXPIRED', 'Expirée')], default='ACTIVE', max_length=10),
        ),
        migrations.RunPython(backfill_expires_at, migrations.RunPython.noop),
    ]
