# Generated by Django 4.2 on 2026-09-24 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0008_post_comments_count_post_shares_count_postuniqueview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustScoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neutral_rating', models.FloatField(default=3.5, help_text='m : note neutre')),
                ('neutral_weight', models.FloatField(default=5.0, help_text='C : poids de la note neutre')),
                ('min_reviews_to_display', models.PositiveIntegerField(default=3)),
            ],
            options={
                'verbose_name': 'Paramètres du Trust Score',
                'verbose_name_plural': 'Paramètres du Trust Score',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'En attente de confirmation'), ('CONFIRMED', 'Confirmée'), ('DECLINED', 'Refusée')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals_to_confirm', to=settings.AUTH_USER_MODEL)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals_initiated', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='marketplace.post')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
