# Generated by Django 4.2 on 2026-09-24 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_marketplacesettings_post_expires_at_and_more'),
        ('reputation', '0002_backfill_trust_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='marketplace.post'),
        ),
    ]
