# Generated by Django 4.2 on 2026-09-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RankingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_views', models.FloatField(default=1.0)),
                ('weight_likes', models.FloatField(default=3.0)),
                ('weight_comments', models.FloatField(default=5.0)),
                ('weight_shares', models.FloatField(default=8.0)),
                ('trust_factor_min', models.FloatField(default=0.8)),
                ('trust_factor_max', models.FloatField(default=1.2)),
                ('recency_half_life_hours', models.FloatField(default=72.0)),
            ],
            options={
                'verbose_name': 'Paramètres de classement',
                'verbose_name_plural': 'Paramètres de classement',
            },
        ),
    ]
